### PR TITLE
fix: Cannot find module 'nuxt-edge'

### PR DESCRIPTION
**Pull request by daliborgogic**
When server is `micro` , `micro.config.js` require `nuxt-edge`.

### CODE REVIEW

**Comment by Codefa** [comment]
to fix this issue install nuxt-edge,

npm i nuxt-edge

Thank you

**Comment by robcresswell** [comment]
@Codefa Nuxt 2 is out now. Using nuxt-edge doesn't make any sense. Please accept the PR :)

**Comment by Codefa** [comment]
> @Codefa Nuxt 2 is out now. Using nuxt-edge doesn't make any sense. Please accept the PR :)

atlease for now to fix the problem need to use nuxt-edge becaue the master files didn't updated

**Comment by robcresswell** [comment]
Awesome!

**Pull request merged**
